GameTable/Models/Author.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int AuthorID { get; set; }
        public string personalPic { get; set; }
        public string Name { get; set; }
        public int Approval { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
    }
}

GameTable/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTable.Models;

namespace GameTable.Controllers
{
    public class AuthorController : Controller
    {
        private GameTableEntities db = new GameTableEntities();

        //
        // GET: /Author/

        public ActionResult Index()
        {
            return View(db.Authors.ToList());
        }

        //
        // GET: /Author/Details/5

        public ActionResult Details(int id = 0)
        {
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        //
        // GET: /Author/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Author/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Authors.Add(author);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(author);
        }

        //
        // GET: /Author/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        //
        // POST: /Author/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Author author)
        {
            if (ModelState.IsValid)
            {
                db.Entry(author).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(author);
        }

        //
        // GET: /Author/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Author author = db.Authors.Find(id);
            if (author == null)
            {
                return HttpNotFound();
            }
            return View(author);
        }

        //
        // POST: /Author/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Author author = db.Authors.Find(id);
            db.Authors.Remove(author);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameTable/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTable.Models;

namespace GameTable.Controllers
{
    public class CategoryController : Controller
    {
        private GameTableEntities db = new GameTableEntities();

        //
        // GET: /Category/

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        //
        // GET: /Category/Details/5

        public ActionResult Details(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Category/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /Category/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Category/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameTable/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTable.Models;

namespace GameTable.Controllers
{
    public class PostController : Controller
    {
        private GameTableEntities db = new GameTableEntities();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.Author).Include(p => p.Category);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "personalPic");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "personalPic", post.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", post.CategoryID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "personalPic", post.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", post.CategoryID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorID = new SelectList(db.Authors, "AuthorID", "personalPic", post.AuthorID);
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Category1", post.CategoryID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

GameTable/Views/Author/Create.cshtml
@model GameTable.Models.Author

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Author</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.personalPic)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.personalPic)
            @Html.ValidationMessageFor(model => model.personalPic)
        </div>
        
        @Html.Hidden("Approval", 0)

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameTable/Views/Author/Delete.cshtml
@model GameTable.Models.Author

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Author</legend>

    <div class="display-label">
         Profile Picture
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.personalPic)
    </div>

    <div class="display-label">
         Name
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         Approval
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Approval)
    </div>

    <div class="display-field">
        Number of Posts
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Posts.Count)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index", "Author")
    </p>
}

GameTable/Views/Author/Details.cshtml
@model GameTable.Models.Author

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Author</legend>

    <div class="display-label">
         Profile Picture
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.personalPic)
    </div>
    <br />
    <div class="display-label">
         Name
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
    <br />
    <div class="display-label">
         Approval Rating
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Approval)
    </div>
    <br />
    <div class="display-field">
        Number of Posts
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Posts.Count)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.AuthorID }) |
    @Html.ActionLink("Back to List", "Index", "Author")
</p>

GameTable/Views/Author/Edit.cshtml
@model GameTable.Models.Author

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Author</legend>

        @Html.HiddenFor(model => model.AuthorID)

        <div class="editor-label">
            @Html.LabelFor(model => model.personalPic)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.personalPic)
            @Html.ValidationMessageFor(model => model.personalPic)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        @Html.Hidden("Approval", 0)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Author")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameTable/Views/Author/Index.cshtml
@model IEnumerable<GameTable.Models.Author>

@{
    ViewBag.Title = "Index";
}

<h2>Authors</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Posts", "Index", "Post")
</p>
<p>
    @Html.ActionLink("Categories", "Index", "Category")
</p>
<table>
    <tr>
        <th>
            Profile Picture
        </th>
        <th>
            Author
        </th>
        <th>
            Approval Rating
        </th>
        <th>
            Number of Posts
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.personalPic)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Approval)
        </td>
        <td>
            @item.Posts.Count
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.AuthorID })
            <br />
            @Html.ActionLink("Details", "Details", new { id=item.AuthorID })
            <br />
            @Html.ActionLink("Delete", "Delete", new { id=item.AuthorID })
        </td>
    </tr>
}

</table>